apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: efk
spec:
  interval: 1m
  chart:
    spec:
      chart: ./elasticsearch
      sourceRef:
        kind: GitRepository
        name: efk
        namespace: efk